### ISSUE TITLE
How to install MDAtoolkits and IMOtoolkits

### ISSUE THREAD

**Issue by liaochenlanruo** [ShawnWx2019/HPC_tidymass#1]
Hi,
Is there any instruction about how to install the packages `MDAtoolkits` and `IMOtoolkits`? Thanks!

**Comment by ShawnWx2019** [comment]
Currently, it is only a testing version and there are still many issues. It is not recommended to use it directly for analysis. However, if you want to try it, you can install these two packages through the following code:

```r
##> MDAtoolkits
devtools::install_github(repo = "ShawnWx2019/MDAtoolkits",ref = 'master')
##> IMOtoolkits
devtools::install_github(repo = "ShawnWx2019/IMOtoolkits")
```

**Comment by liaochenlanruo** [comment]
Thanks! The packages were installed successfully with the following commands:

```shell
mamba install r-rstatix bioconductor-pcatools bioconductor-ropls r-bs4dash r-shinyjqui
``` 

```r
remotes::install_github('aberHRML/classyfireR')

 ##> MDAtoolkits
remotes::install_github(repo = "ShawnWx2019/MDAtoolkits",ref = 'master')
##> IMOtoolkits
remotes::install_github(repo = "ShawnWx2019/IMOtoolkits")
```
